services:
    app:
        build:
            context: .
            args:
                NODE_ENV: production
        env_file: .env.production
        container_name: todolist
        environment:
            - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
            - NODE_ENV=production
            - PORT=${APP_PORT}
        ports:
            - '${APP_PORT}:${APP_PORT}'
        depends_on:
            - db
        restart: always
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1G

    db:
        image: postgres:13-alpine
        container_name: postgres-db
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: always
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1G

volumes:
    postgres-data:
        driver: local
