const DB_USER = {
    MIN_USERNAME_LENGTH: 5,
    MAX_USERNAME_LENGTH: 50,
    MIN_EMAIL_LENGTH: 5,
    MAX_EMAIL_LENGTH: 150,
    MIN_PASSWORD_LENGTH: 5,
    MAX_PASSWORD_LENGTH: 200,
    MAX_REFRESH_TOKEN_LENGTH: 400,
};

const DB_TASK = {
    MIN_TITLE_LENGTH: 1,
    MAX_TITLE_LENGTH: 150,
    MIN_DESCRIPTION_LENGTH: 0,
    MAX_DESCRIPTION_LENGTH: 400,
};

export { DB_USER, DB_TASK };
